// Generated by https://quicktype.io

export interface ITwilioToken {
  token: string;
}


// Generated by https://quicktype.io
// Generated by https://quicktype.io

// To parse this data:
//
//   import { Convert, ICallResponse } from "./file";
//
//   const iCallResponse = Convert.toICallResponse(json);

export interface ICallIo {
    Called:        string;
    ToState:       string;
    CallerCountry: string;
    Direction:     string;
    CallerState:   string;
    ToZip:         string;
    CallSid:       string;
    To:            string;
    CallerZip:     string;
    ToCountry:     string;
    StirVerstat:   string;
    CallToken:     string;
    CalledZip:     string;
    ApiVersion:    Date;
    CalledCity:    string;
    CallStatus:    string;
    From:          string;
    AccountSid:    string;
    CalledCountry: string;
    CallerCity:    string;
    ToCity:        string;
    FromCountry:   string;
    Caller:        string;
    FromCity:      string;
    CalledState:   string;
    FromZip:       string;
    FromState:     string;
}

