// Generated by https://quicktype.io

export interface IAuthResponse {
  data:  IUserData;
  token: string;
}

export interface IUserData {
  fullname: string;
  email:    string;
  phone:    string;
  google:   boolean;
  isVerify: boolean;
  createAt: string;
  status:   boolean;
  roles:    Role[];
  country?:  Country;

  location: string;
  mrn: string;
  client: string;

  agency?: IAgency;
}


export interface Country {
  id:            string;
  name:          string;
  timeZone:      string;
  isoAlphaThree: string;
  moneyCode:     string;
  moneySymbol:   string;
  prefixPhone:   string;
  img:           string;
}

export interface Role {
  id:   string;
  name: string;
  code: string;
}


// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface IMenuUserResponse {
  data:   IUserData;
  allowMenu: Allow[];
  allows: Allow[];
}

export interface Allow {
  id:      string;
  actions: string[];
  menu:    Menu;
  children: Allow[];
}

export interface Menu {
  status:       boolean;
  userCreate:   string;
  createAt:     string;
  id:           string;
  name:         string;
  icon:         string;
  webUrl:       string;
  apiUrl:       string;
  patherMenuId: null | string;
  hidden:       boolean;
  haveTranslate: boolean;
  translate:    string;
  // actions?:      string[];
}

// export interface IUserData {
//   status:       boolean;
//   id:           string;
//   fullname:     string;
//   email:        string;
//   google:       boolean;
//   isVerify:     boolean;
//   agency: IAgency;
// }

export interface IAgency {
  status:        boolean;
  userCreate:    string;
  createAt:      string;
  id:            string;
  bussinnesName: string;
  document:      string;
  address:       string;
  email:         string;
  phone:         string;
  costPerMinute: string;
  logoUrl:       string;
  backdropUrl:   string;
  country:       Country;
}

export interface Country {
  status:        boolean;
  userCreate:    string;
  createAt:      string;
  id:            string;
  name:          string;
  isoAlphaThree: string;
  moneyCode:     string;
  moneySymbol:   string;
  prefixPhone:   string;
  img:           string;
}
