// Generated by https://quicktype.io

export interface ICountryListResponse {
  data:  ICountry[];
  total: number;
}

export interface ICountry {
  status:        boolean;
  userCreate:    string;
  createAt:      string;
  id:            string;
  name:          string;
  isoAlphaThree: string;
  moneyCode:     string;
  moneySymbol:   string;
  prefixPhone:   string;
  img:           string;
}
