// Generated by https://quicktype.io

export interface INomenclatureResponse {
  data:  INomenclature[];
  total: number;
}

export interface INomenclature {
  status:     boolean;
  userCreate: string;
  createAt:   string;
  id:         string;
  label:      string;
  value:      string;
  // module:     string;
}
