// Generated by https://quicktype.io

export interface IListOrganizationResponse {
  data:  IOrganization[];
  total: number;
}

export interface IListOrganizationByIdResponse {
  data:  IOrganization;
}

export interface IOrganization {
  status:        boolean;
  createAt:      string;
  id:            string;
  bussinnesName: string;
  address:       string;
  document:      string;
  email:         string;
  phone:         string;
  costPerMinute: string;
  country:       Country;
}

export interface Country {
  id:            string;
  name:          string;
  isoAlphaThree: string;
  moneyCode:     string;
  moneySymbol:   string;
}

