// Generated by https://quicktype.io

export interface IRoleMenuResponse {
  pathers:  IMenuRole[];
  children: IMenuRole[];
}

export interface IMenuRole {
  status:       boolean;
  name:         string;
  id:           string;
  icon:         string;
  webUrl:       string;
  apiUrl:       string;
  patherMenuId: null | string;
  actions:      string[];

  children?: IMenuRole[];
  haveChildren: boolean;
}


// Generated by https://quicktype.io

export interface IMenuResponseRole {
  data: IMenuRole[];
}


