// Generated by https://quicktype.io

export interface IRoleMenuResponse {
  pathers:  IMenuRole[];
  children: IMenuRole[];
}

export interface IMenuRole {
  status:       boolean;
  name:         string;
  id:           string;
  icon:         string;
  webUrl:       string;
  apiUrl:       string;
  patherMenuId: null | string;
  actions:      IAllow[];

  children?:    IMenuRole[];
  haveChildren: boolean;

  selected:     boolean;
}


export interface IAllow {
  action:       string;
  selected:     boolean;
}

// Generated by https://quicktype.io

export interface IMenuResponseRole {
  data: IMenuRole[];
}


// Generated by https://quicktype.io

export interface IRoleResponse {
  data:  IRole[];
  total: number;
}

export interface IRole {
  status:      boolean;
  userCreate:  string;
  createAt:    string;
  userUpdate:  null;
  updateAt:    null;
  userDelete:  null;
  deleteAt:    null;
  id:          string;
  name:        string;
  code:        string;
  description: string;
}


// Generated by https://quicktype.io

export interface IRoleByIDResponse {
  data: IRoleAllow;
}



export interface IRoleAllow {
  status:        boolean;
  userCreate:    string;
  createAt:      string;
  userUpdate:    null;
  updateAt:      null;
  userDelete:    null;
  deleteAt:      null;
  id:            string;
  name:          string;
  code:          string;
  description:   string;
  roleMenuAllow: RoleMenuAllow[];
}

export interface RoleMenuAllow {
  id:       string;
  actions:  string[];
  createAt: string;
}
