// Generated by https://quicktype.io

export interface ITimezoneListresponse {
  data:  ITimezone[];
  total: number;
}

export interface ITimezone {
  status:     boolean;
  userCreate: string;
  createAt:   string;
  id:         string;
  name:       string;
  timeZone:   string;
}
