// Generated by https://quicktype.io

export interface IMenuResponse {
  data:  IMenu[];
  total: number;
}

export interface IMenuByIdResponse {
  data:  IMenu;
}

export interface IMenu {
  status:       boolean;
  userCreate:   string;
  createAt:     string;
  id:           string;
  name:         string;
  icon:         string;
  webUrl:       string;
  apiUrl:       string;
  hidden:       boolean;
  order:        number;
  haveTranslate: boolean;
  translate: string;
  patherMenuId: null | string;
  actions:      string[];
}
