// Generated by https://quicktype.io

export interface ICampusListResponse {
  data:  ICampus[];
  total: number;
}

export interface ICampus {
  status:     boolean;
  userCreate: string;
  createAt:   string;
  id:         string;
  campusName: string;
  city:       string;
  address:    null;
}
