// Generated by https://quicktype.io

export interface ICustomerTypeListResponse {
  data:  ICustomerType[];
  total: number;
}

export interface ICustomerType {
  status:       boolean;
  userCreate:   null;
  createAt:     string;
  id:           string;
  customerType: string;
}
