// Generated by https://quicktype.io

export interface ICustomerByIdResponse {
  data:  ICustomer;
}

// Generated by https://quicktype.io

export interface ICustomerListResponse {
  data:  ICustomer[];
  total: number;
}

export interface ICustomer {
  status:       boolean;
  userCreate:   null;
  createAt:     string;
  id:           string;
  customerName: string;
  address:      string;
  cityName:     string;
  postalCode:   string;
  email:        string;
  phone:        null;
  countryCode:  string;
  agencyId:     null;
  timezone:     Timezone;
  departments:  IDepartment[];

  customerType: ICustomerType;
  rates:        Rate[];
  activeNumbers: IActiveNumber[];
}

export interface IActiveNumber {
  status:     boolean;
  userCreate: string;
  createAt:   string;
  id:         string;
  name:       string;
  number:     string;
  rate:       string;
}


export interface Rate {
  status:     boolean;
  userCreate: string;
  createAt:   string;
  id:         string;
  type:       string;
  rate:       string;
}

export interface ICustomerType {
  status:       boolean;
  userCreate:   null;
  createAt:     string;
  id:           string;
  customerType: string;
}

export interface IDepartment {
  status:     boolean;
  userCreate: null;
  createAt:   string;
  id:         string;
  departmentName: string;
  accessCode: string;
}

export interface Timezone {
  status:       boolean;
  userCreate:   string;
  createAt:     string;
  id:           string;
  zoneName:     string;
  countryCode:  string;
  abbreviation: string;
  timeStart:    string;
  gmtOffset:    number;
  dst:          string;
}


