// Generated by https://quicktype.io

export interface IIdiomListResponse {
  data:  IIdiom[];
  total: number;
}

export interface IIdiom {
  status:                 boolean;
  userCreate:             string;
  createAt:               string;
  id:                     string;
  priority:               number;
  isVideoBackstopStaffed: boolean;
  isSignLanguage:         boolean;
  englishName:            string;
  name:                   string;
  nativeName:             string;
  localizedName:          string;
  code:                   string;
}
