// Generated by https://quicktype.io

export interface IInterpreterListResponse {
  data:  IInterpreter[];
  total: number;
}

export interface IInterpreterByIdResponse {
  data:  IInterpreter;
}

export interface IInterpreter {
  status:         boolean;
  createAt:       string;
  id:             string;
  name:           string;
  surname:        string;
  fullname:       string;
  email:          string;
  phone:          null | string;
  gender:         string;
  countryCode:    string;
  roles:          IRoleRef[];
  agency:         IAgency;
  timezone:       Timezone;
  nativeLanguage: INativeLanguageRef | null;
}

export interface IAgency {
  status:        boolean;
  userCreate:    string;
  createAt:      string;
  id:            string;
  bussinnesName: string;
  document:      string;
  address:       string;
  email:         string;
  phone:         string;
  costPerMinute: string;
  logoUrl:       string;
  backdropUrl:   string;
}

export interface INativeLanguageRef {
  id:          string;
  countryCode: string;
  language:    string;
  isOfficial:  string;
  percentage:  string;
}

export interface IRoleRef {
  id:   string;
  name: string;
}

export interface Timezone {
  status:       boolean;
  userCreate:   string;
  createAt:     string;
  id:           string;
  zoneName:     string;
  countryCode:  string;
  abbreviation: string;
  timeStart:    string;
  gmtOffset:    number;
  dst:          string;
}
