// Generated by https://quicktype.io

export interface ILanguageListResponse {
  data:  ILanguage[];
  total: number;
}

export interface ILanguage {
  id:          string;
  countryCode: string;
  language:    string;
  isOfficial:  IsOfficial;
  percentage:  string;
}

export enum IsOfficial {
  F = "F",
  T = "T",
}
