// Generated by https://quicktype.io

export interface IOrganizationListResponse {
  data:  IOrganization[];
  total: number;
}


export interface IOrganizationByIdResponse {
  data:  IOrganization;
}

export interface IOrganization {
  status:        boolean;
  createAt:      string;
  id:            string;
  bussinnesName: string;
  document:      string;
  address:       string;
  email:         null | string;
  phone:         null | string;
  costPerMinute: string;
  rates:        Rate[];
}

export interface Rate {
  status: boolean;
  id:     string;
  type:   string;
  rate:   string;
}




