// Generated by https://quicktype.io

export interface IInterpreterProfileResponse {
  data: IProfileInterpreter;
}

export interface IProfileInterpreter {
  status:          boolean;
  createAt:        string;
  id:              string;
  name:            string;
  surname:         string;
  fullname:        string;
  email:           string;
  phone:           string;
  gender:          string;
  countryCode:     string;
  nativeLanguage:  NativeLanguage;
  targetLanguages: TargetLanguage[];
  timezone:        Timezone;
  rates:           Rate[];
}

export interface NativeLanguage {
  id:       string;
  language: string;
}

export interface Rate {
  status: boolean;
  id:     string;
  type:   string;
  rate:   string;
}

export interface TargetLanguage {
  id:             string;
  isSignLanguage: boolean;
  name:           string;
}

export interface Timezone {
  id:       string;
  zoneName: string;
}


// Generated by https://quicktype.io


export interface IRateUpdateResponse {
  status:      boolean;
  userCreate:  string;
  createAt:    string;
  id:          string;
  name:        string;
  surname:     string;
  fullname:    string;
  address:     null;
  cityname:    null;
  postalcode:  null;
  email:       string;
  phone:       string;
  password:    string;
  gender:      string;
  google:      boolean;
  socket:      null;
  img:         null;
  fcmToken:    null;
  isVerify:    boolean;
  codeVerify:  null;
  tokenVerify: null;
  countryCode: string;
  rates?:      Rate[];
  userUpdate?: string;
  updateAt?:   string;
  userDelete?: null;
  deleteAt?:   null;
}

