// Generated by https://quicktype.io

export interface IInterpreterProfileResponse {
  data: IProfileInterpreter;
}

export interface IProfileInterpreter {
  status:          boolean;
  createAt:        string;
  id:              string;
  name:            string;
  surname:         string;
  fullname:        string;
  email:           string;
  phone:           string;
  gender:          string;
  countryCode:     string;
  nativeLanguage:  NativeLanguage;
  targetLanguages: TargetLanguage[];
  timezone:        Timezone;
  rates:           Rate[];
  officeHours:     OfficeHour[];
  contacts:        Contact[];
  resumeUrl:       string;
  resumeName:      string;
  resumeFirebase:  string;
  resumeType:      string;
}

export interface OfficeHour {
  status:    boolean;
  id:        string;
  dayName:   string;
  timeStart: string;
  timeEnd:   string;
}

export interface NativeLanguage {
  id:       string;
  language: string;
}

export interface Rate {
  status: boolean;
  id:     string;
  idiom:   any;
  type:   string;
  rate:   string;
}

export interface TargetLanguage {
  id:             string;
  isSignLanguage: boolean;
  name:           string;
}

export interface Timezone {
  id:       string;
  zoneName: string;
}


// Generated by https://quicktype.io


export interface IRateUpdateResponse {
  status:      boolean;
  userCreate:  string;
  createAt:    string;
  id:          string;
  name:        string;
  surname:     string;
  fullname:    string;
  address:     null;
  cityname:    null;
  postalcode:  null;
  email:       string;
  phone:       string;
  password:    string;
  gender:      string;
  google:      boolean;
  socket:      null;
  img:         null;
  fcmToken:    null;
  isVerify:    boolean;
  codeVerify:  null;
  tokenVerify: null;
  countryCode: string;
  rates?:      Rate[];
  userUpdate?: string;
  updateAt?:   string;
  userDelete?: null;
  deleteAt?:   null;
}



// Generated by https://quicktype.io

export interface IUpdateContactResponse {
  status:      boolean;
  userCreate:  string;
  createAt:    string;
  id:          string;
  code:        null;
  name:        string;
  surname:     string;
  fullname:    string;
  address:     null;
  cityname:    null;
  postalcode:  null;
  email:       string;
  phone:       null;
  password:    string;
  gender:      string;
  google:      boolean;
  socket:      string;
  img:         string;
  fcmToken:    string;
  isVerify:    boolean;
  resetPsw:    boolean;
  codeVerify:  string;
  tokenVerify: string;
  countryCode: string;
  location:    null;
  mrn:         null;
  client:      null;
  userUpdate:  string;
  updateAt:    string;
  contacts:    Contact[];
  userDelete:  null;
  deleteAt:    null;
}

export interface Contact {
  status:      boolean;
  userCreate:  string;
  createAt:    string;
  userUpdate:  null;
  updateAt:    null;
  userDelete:  null;
  deleteAt:    null;
  id:          string;
  contactType: string;
  contact:     string;
}


