// Generated by https://quicktype.io

import { Timezone } from "./interpreter.interface";

export interface IInterpreterProfileResponse {
  data: IProfileInterpreter;
}

export interface IProfileInterpreter {
  status:          boolean;
  createAt:        string;
  id:              string;
  name:            string;
  surname:         string;
  fullname:        string;
  email:           string;
  phone:           null;
  gender:          string;
  countryCode:     string;
  nativeLanguage:  NativeLanguage;
  targetLanguages: TargetLanguage[];
  timezone:       Timezone;
}

export interface NativeLanguage {
  id:       string;
  language: string;
}

export interface TargetLanguage {
  id:             string;
  isSignLanguage: boolean;
  name:           string;
}
